### ISSUE TITLE
error code 1 and singal null when running node main.js for openai

### ISSUE THREAD

**Issue by Sonicfai** [mindcraft-bots/mindcraft#138]
Using chat settings: { model: 'gpt-3.5-turbo', api: 'openai' }
file:///C:/Users/Fabian/Downloads/mindcraft-main/mindcraft-main/src/utils/keys.js:17
        throw new Error(`API key "${name}" not found in keys.json or environment variables!`);    
              ^

Error: API key "OPENAI_API_KEY" not found in keys.json or environment variables!
    at getKey (file:///C:/Users/Fabian/Downloads/mindcraft-main/mindcraft-main/src/utils/keys.js:17:15)
    at new GPT (file:///C:/Users/Fabian/Downloads/mindcraft-main/mindcraft-main/src/models/gpt.js:15:25)
    at new Prompter (file:///C:/Users/Fabian/Downloads/mindcraft-main/mindcraft-main/src/agent/prompter.js:43:31)
    at Agent.start (file:///C:/Users/Fabian/Downloads/mindcraft-main/mindcraft-main/src/agent/agent.js:14:25)
    at file:///C:/Users/Fabian/Downloads/mindcraft-main/mindcraft-main/src/process/init-agent.js:27:13
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.16.0
Agent process exited with code 1 and signal null
Agent process exited too quickly. Killing entire process. Goodbye.

**Comment by Sonicfai** [comment]
the api key is in there too

**Comment by testeraccount-645** [comment]
same problem too

**Comment by FantomWolf182** [comment]
same problem

**Comment by Amethyst222** [comment]
I think you might have replaced "OPENAI_API_KEY" with the actual api key, which you are supposed it keep and put the actual api key in quotes to the right

**Comment by FantomWolf182** [comment]
i didn't

**Comment by OngMSJ** [comment]
I also have the same problem :<

**Comment by uukelele** [comment]
Make sure to rename `keys.example.json` to `keys.json`.

**Comment by uukelele** [comment]
Reopen the issue if required.
