### ISSUE TITLE
help me im using gemini api i also changed the bot to "gemini" from "andy"

### ISSUE THREAD

**Issue by ianisadin** [mindcraft-bots/mindcraft#260]
[Done] exited with code=0 in 6.441 seconds

[Running] node "c:\Users\ianis\Downloads\mindcraft-main\main.js"
[ './andy.json' ]
Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
file:///c:/Users/ianis/Downloads/mindcraft-main/src/utils/keys.js:17
        throw new Error(`API key "${name}" not found in keys.json or environment variables!`);
              ^

Error: API key "OPENAI_API_KEY" not found in keys.json or environment variables!
    at getKey (file:///c:/Users/ianis/Downloads/mindcraft-main/src/utils/keys.js:17:15)
    at new GPT (file:///c:/Users/ianis/Downloads/mindcraft-main/src/models/gpt.js:16:25)
    at new Prompter (file:///c:/Users/ianis/Downloads/mindcraft-main/src/agent/prompter.js:55:31)
    at Agent.start (file:///c:/Users/ianis/Downloads/mindcraft-main/src/agent/agent.js:16:25)
    at file:///c:/Users/ianis/Downloads/mindcraft-main/src/process/init-agent.js:33:13
    at ModuleJob.run (node:internal/modules/esm/module_job:234:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:473:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5)

Node.js v20.18.0
Agent process exited with code 1 and signal null
Agent process ./andy.json exited too quickly and will not be restarted.
All agent processes have ended. Exiting.

[Done] exited with code=0 in 7.943 seconds

**Comment by Shroototem** [comment]
Make sure you have set the correct profile uncommented and set the model parameters correctly.
**settings.js**
```js
"profiles": [
    // "./andy.json",
    // "./profiles/andy_npc.json",
    // "./profiles/gpt.json",
    "./profiles/gemini.json",
    // "./profiles/claude.json",
    // "./profiles/llama.json",
    // "./profiles/qwen.json",
],
```
**gemini.json**
```js
"model": "gemini-1.5-flash",
```
