### ISSUE TITLE
OpenChat error

### ISSUE THREAD

**Issue by Shandelier** [mindcraft-bots/mindcraft#369]
i'm getting error when i send any message to the bot. here is the log from docker:

```
app-1  | Examples initialized.
app-1  | andy logging into minecraft...
app-1  | andy logged in!
app-1  | andy spawned.
app-1  | received message from system : Say hello world and your name
app-1  | Saved memory to: ./bots/andy/memory.json
app-1  | selected examples:
app-1  | Example: say hi to john_goodman
app-1  | Example: miner_32: Hey! What are you up to?
app-1  | Awaiting openai api response...
app-1  | Received.
app-1  | andy full response to system: ""Hello world! I'm andy!""
app-1  | Attempting to translate: Hello world! I'm andy!
app-1  | Translation result: Hello world! I'm andy!
app-1  | Error in openChat: {}
app-1  | Unhandled Rejection at: {
app-1  |   promise: Object [Promise] {},
app-1  |   reason: {},
app-1  |   stack: "TypeError: Cannot read properties of undefined (reading 'length')\n" +
app-1  |     '  at EventEmitter.respondFunc (file:///app/src/agent/agent.js:115:41)\n' +
app-1  |     '  at EventEmitter.emit (node:events:507:28)\n' +
app-1  |     '  at EventEmitter.<anonymous> (/app/node_modules/mineflayer/lib/plugins/chat.js:85:13)\n' +
app-1  |     '  at EventEmitter.emit (node:events:519:35)\n' +
app-1  |     '  at Client.<anonymous> (/app/node_modules/mineflayer/lib/plugins/chat.js:131:9)\n' +
app-1  |     '  at Client.emit (node:events:507:28)\n' +
app-1  |     '  at Client.<anonymous> (/app/node_modules/minecraft-protocol/src/client/chat.js:203:14)\n' +
app-1  |     '  at Client.emit (node:events:507:28)\n' +
app-1  |     '  at emitPacket (/app/node_modules/minecraft-protocol/src/client.js:83:12)\n' +
app-1  |     '  at FullPacketParser.<anonymous> (/app/node_modules/minecraft-protocol/src/client.js:112:9)'
app-1  | }
app-1  | SES_UNHANDLED_REJECTION: {}
app-1  | Agent process exited with code 1 and signal null
app-1  | Restarting agent...
app-1  | Removing unpermitted intrinsics
app-1  |   Removing intrinsics.Promise.try
app-1  | Starting agent with profile: ./andy.json
app-1  | Starting agent initialization with profile: ./andy.json
app-1  | Initializing action manager...
app-1  | Initializing prompter...
app-1  | Using chat settings: { model: 'gpt-4o-mini', api: 'openai' }
app-1  | Using embedding settings: { api: 'openai' }
app-1  | Initializing history...
app-1  | Initializing coder...
app-1  | Initializing npc controller...
app-1  | Initializing memory bank...
app-1  | Initializing self prompter...
app-1  | Initializing examples...
app-1  | (node:29) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
app-1  | (Use `node --trace-deprecation ...` to show where the warning was created)
app-1  | Examples initialized.
app-1  | andy logging into minecraft...
app-1  | Loaded memory: 
app-1  | andy logged in!
app-1  | andy spawned.
app-1  | received message from system : Agent process restarted.
app-1  | Saved memory to: ./bots/andy/memory.json
app-1  | selected examples:
app-1  | Example: abc: stop
app-1  | Example: say hi to john_goodman
app-1  | Awaiting openai api response...
app-1  | Received.
app-1  | andy full response to system: ""Hello world! I'm Andy! ""
app-1  | Attempting to translate: Hello world! I'm Andy! 
app-1  | Translation result: Hello world! I'm Andy! 
app-1  | Error in openChat: {}

```

**Comment by Shandelier** [comment]
Previous merge doesn't have this error

**Comment by uukelele** [comment]
Try using the latest version of mindcraft as it should have solved this issue.

If your problem persists, please feel free to reopen this issue.
